// Code generated by MockGen. DO NOT EDIT.
// Source: code.go
//
// Generated by this command:
//
//	mockgen -source=code.go -destination=mocks/mock_validator.go -package=mocks Validator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// Validator mocks base method.
func (m *MockValidator) Validator(ctx context.Context, value int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validator", ctx, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validator indicates an expected call of Validator.
func (mr *MockValidatorMockRecorder) Validator(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validator", reflect.TypeOf((*MockValidator)(nil).Validator), ctx, value)
}
