version: '3'

vars:
  PROTO_DIR: grps/01      # ← Указываем папку с .proto файлами
  GEN_DIR: gen          # ← Куда генерировать код

tasks:
  generate:
    desc: "Generate Go + gRPC code from protobuf"
    cmds:
      - |
        protoc \
          -I {{.PROTO_DIR}} \
          --go_out={{.GEN_DIR}} \
          --go_opt=paths=source_relative \
          --go-grpc_out={{.GEN_DIR}} \
          --go-grpc_opt=paths=source_relative \
          {{.PROTO_DIR}}/*.proto